sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - '7'
env:
- CXX=clang++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm test

#cache:
#  directories:
#    - node_modules
