# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ windows-2019, ubuntu-18.04, macos-10.15 ]
        os: [ ubuntu-18.04 ]
        # node-version: [ 10.x, 12.x, 13.x ]
        node-version: [  12.x ]

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v2
    - name: ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm -g i willbe@alpha
    - run: will .build
    - run: npm test
    - run: npm run node-pre-gyp-package && npm run node-pre-gyp-github-release
      if: "success() == true && startsWith(github.event.head_commit.message, 'version')"
